apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: test
  namespace: frr-k8s-system
spec:
  bgp:
    routers:
    - asn: 64512
      neighbors:
      - address: 172.30.0.3
        asn: 4200000000
        ebgpMultiHop: true
        passwordSecret:
          name: passwordsecret
          namespace: frr-k8s-system
        port: 180
        toAdvertise:
          allowed:
            mode: all
      - address: 172.18.0.6
        asn: 4200000000
        port: 179
        toAdvertise:
          allowed:
            prefixes:
            - 192.168.2.0/24
      prefixes:
      - 192.168.2.0/24
      - 192.169.2.0/24
---
apiVersion: v1
kind: Secret
metadata:
  name: passwordsecret
  namespace: frr-k8s-system
data:
  password: passwordbase64
type: kubernetes.io/basic-auth
