apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: raw-config
  namespace: frr-k8s-system
spec:
  raw:
    rawConfig: |-
      router bgp 64512
        address-family ipv4 unicast
          network 192.169.3.1/32
        exit-address-family
